version: '3.8'
services:
  app:
    container_name: spadge-app
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "8765:8765"
    env_file:
      - .env

  postgres:
    container_name: spadge-main_db
    build: 
      context: .
      dockerfile: ./infra/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "main_db"
      TZ: "Asia/Tokyo"
    entrypoint: >
      bash -c "
      chown -R postgres:postgres /var/lib/postgresql/data &&
      docker-entrypoint.sh postgres
      "
